// Generated by dagger.internal.codegen.ComponentProcessor (https://google.github.io/dagger).
package com.tangzhen.data.prefs;

import android.content.Context;
import dagger.internal.Factory;
import javax.inject.Provider;

public final class AppPreferencesHelper_Factory implements Factory<AppPreferencesHelper> {
  private final Provider<Context> contextProvider;

  private final Provider<String> mPrefsNameProvider;

  public AppPreferencesHelper_Factory(
      Provider<Context> contextProvider, Provider<String> mPrefsNameProvider) {
    assert contextProvider != null;
    this.contextProvider = contextProvider;
    assert mPrefsNameProvider != null;
    this.mPrefsNameProvider = mPrefsNameProvider;
  }

  @Override
  public AppPreferencesHelper get() {
    return new AppPreferencesHelper(contextProvider.get(), mPrefsNameProvider.get());
  }

  public static Factory<AppPreferencesHelper> create(
      Provider<Context> contextProvider, Provider<String> mPrefsNameProvider) {
    return new AppPreferencesHelper_Factory(contextProvider, mPrefsNameProvider);
  }
}
